= Demo Post
Jonathan Bullock
:jbake-author: René Schwietzke
:jbake-type: post
:jbake-status: published
:jbake-tags: blog, asciidoc
:description: This is a description of fourth post
:idprefix:

This the preamble of the post and is rendered differently.

== Start
This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share.

This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share. This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share.This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share.This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share.

=== Headline3
My new blog is using https://jbake.org[JBake] as the static site generator and I also
opted for AsciiDoc as the markup because a future book of mine will be written with it,
so I need a testing ground.

==== Headline 4
My name contains a non-ASCII character: é. Half of the IT-world does not get that right, but this is another topic for a blog post. So when you put that character in `jbake.properties`, it did not arrive properly in the Freemarker output. This applies to Jbake 2.6.7. Just wanted to give 2.7.0-RC6 a try and voila, it works like a charm.

===== Headline 5
Looking forward to the release of 2.7.0.

== Headline 2
This was not meant to be the first entry in my new blog, but accidentally this
is interesting information to share.
